on: [push]

jobs:
  notify:
    runs-on: ubuntu-latest
    name: RunDocs
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      
      - name: Update22 latest version in realtime database
        uses: vinodtiru/firebase-trigger@qa
        with:
          credentials: ${{ secrets.FIREBASE_CREDENTIALS }}
          databaseUrl: https://learn-simple-code.firebaseio.com
          databaseType: firestore
          path: version
          doc: ImsHg08RNhDt4wvJrlBO
          value: '{"make": "audiv2"}'
